### ISSUE TITLE
shinycell plot export issue

### ISSUE THREAD

**Issue by islet-data-tinkerer** [Gaulton-Lab/HPAP-scRNA-seq#1]
Thanks for making such a cool and useful tool.

I am trying to export PDF from the bubbleplot maker on the shinycell browser. I've tried firefox and chrome. In firefox, it opens a new tab and nothing happens. I disabled ad blockers. In chrome it tries to download an HTML file, but even that fails when I say ok. 

For now, I can just copy the image from the browser, but a PDF would be nice to have a vectorized file to tweak the figure a little bit. 

Thanks!

**Comment by relgamal** [comment]
Hi @neococo -thank you for using our tools! I tested on my end and I can see this problem as well, I appreciate you bringing it to our attention. I'll look into it and update this thread once we've resolved the issue. I agree that having the vector files is useful!

Best,

Ruth

**Comment by relgamal** [comment]
Hi @neococo , this issue should be resolved now.

**Comment by islet-data-tinkerer** [comment]
Thanks it works for me now, too!

**Comment by islet-data-tinkerer** [comment]
i'm not sure what happened, but it stopped working for me again. I came back to remake some plots but it tries to save a .html file and fails in Chrome, or in firefox it just opens a new browser tab but no download, either for PDF or PNG. Seems to only occur on the bubbleplot tab, for example the proportion plot export to PDF is functional.

Thanks for your help!

**Comment by relgamal** [comment]
Hi @neococo - we appreciate you bringing this to our attention again! We made a minor update to the object on ShinyCell so it must be the same issue we originally had. We'll sort that out on our end and update you here when that's fixed.

**Comment by relgamal** [comment]
Hi @neococo, thanks for your patience. This problem should be solved now!
