### ISSUE TITLE
cellxgene & azimuth can't be reached. 

### ISSUE THREAD

**Issue by rampade1** [Gaulton-Lab/HPAP-scRNA-seq#2]
I'm trying to reach the tools cellxgene & azimuth and they can't be reached.

**Comment by relgamal** [comment]
Hi @rampade1 – I apologize for missing this message! If you're still interested in using these resources and having trouble accessing them, please reach out. I was able to load both CellxGene and Azimuth successfully today (2/29/24).

Ruth
