### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by swmishra33** [Gaulton-Lab/HPAP-scRNA-seq#3]
Hello, 
I hope this message finds you well. I am writing to inform you that I am encountering difficulties accessing some of the links on your website (link below), particularly those for Cellxgene and ShinyCell, that I am interested in. Could you kindly investigate this issue?

Thank you for your assistance.

Best regards,
Swati Mishra

**Comment by swmishra33** [comment]
http://www.gaultonlab.org/pages/Islet_expression_HPAP.html

**Comment by Parul-Kudtarkar** [comment]
Hello Swati,

Thank you for notifying us. The issue has been fixed, and the links for Cellxgene and ShinyCell are now working. Please feel free to try again, and let us know if you encounter any further issues.
