### ISSUE TITLE
unable to access 'shinycell' in isletgenomics.org

### ISSUE THREAD

**Issue by coatekc** [Gaulton-Lab/HPAP-scRNA-seq#4]
To whom this may concern - for over 1 week now, I have been unable to access shiny cell in your isletgenomics.org webpage

**Comment by Parul-Kudtarkar** [comment]
Hello @coatekc 

Thank you for notifying us. The issue has been fixed, and the links for ShinyCell are now working. Please feel free to try again, and let us know if you encounter any further issues.
